stages:
  - build
  - lint
  # - test
  - staging
  - ready to production
  - production

build:
  stage: build
  tags: [gitlab-org]
  before_script:
    - echo "Building static web page..."
    # - mkdir -p /usr/src/app
    # - cp -r ./ /usr/src/app/
    - cd best-choice
    - apt-get update -y
    - apt-get install npm -y
  script:
    - npm install
    - npm run build
  after_script:
    - cd -
    - echo "Build done"

lint back:
  stage: lint
  tags: [gitlab-org]
  before_script:
    - echo "Linting..."
    - cd best-choice-backend
    - apt-get update -y
    - apt-get install npm -y
  after_script:
    - cd -
    - echo "Linting done"
  script:
    - npm install eslint -g
    - eslint app/ index.js

lint front:
  stage: lint
  tags: [gitlab-org]
  before_script:
    - echo "Linting..."
    - cd best-choice
    - apt-get update -y
    - apt-get install npm -y
  after_script:
    - cd -
    - rcho "Linting done"
  script:
    - npm install eslint -g
    - eslint src/

.test front:
  stage: test
  tags: [gitlab-org]
  before_script:
    - echo "Testing..."
    - cd best-choice
    - apt-get update -y
    - apt-get install npm -y
  after_script:
    - cd -
    - echo "Testing done"
  script:
    - npm run test

.staging-deploy-hidden: &staging-deploy-anchor
  stage: staging
  tags: [gitlab-org]
  when: manual
  before_script:
    - echo "Starting staging deploy"
  script:
    - echo $CI_BUILD_NAME
  after_script:
    - echo "Staging deploy completed"

deploy to stg1:
  <<: *staging-deploy-anchor

deploy to stg2:
  <<: *staging-deploy-anchor

approve:
  stage: ready to production
  tags: [gitlab-org]
  when: manual
  script:
    - mkdir -p .ci_status
    - echo $(date +%s) > .ci_status/approved

NOT approve:
  stage: ready to production
  tags: [gitlab-org]
  when: manual
  script:
    - mkdir -p .ci_status
    - echo $(date +%s) > .ci_status/not_approved

deploy to production:
  stage: production
  tags: [gitlab-org]
  when: manual
  script:
    - if [[ $(cat .ci_status/not_approved) > $(cat .ci_status/approved) ]]; then echo "Нужно разрешение от релиз-инженера"; exit 1; fi
    - echo "Deployed to prod"
